import { Buffer } from 'node:buffer'
import { parseResourceLocation } from '../../util/minecraftUtil'
import type { IRenderedAnimation } from '../animationRenderer'
import type { IRenderedRig } from '../rigRenderer'
import type { ExportedFile } from '../util'
import { decomposeTsb, type DecomposedTsb } from './decomposeTsb'

const BONE_TYPES = ['bone', 'text_display', 'item_display', 'block_display']

// TSB Optimized Export の global キュー管理用 storage。 全 blueprint 共有、 minecraft:tick タグに
// 登録した animated_java:global/load_tick がここを監視して round-robin で各 bp の load/step を呼ぶ。
// 詳細 : docs/tsb-known-issues/parallel-project-load.md。
const GLOBAL_STORAGE_NS = 'aj.global'

export interface CreateAnimationStorageTsbOptions {
	blueprintId: string
	quantizationDigits: number
	cellsPerTick: number
	maxLineBytes: number
}

export interface CreateAnimationStorageTsbResult {
	files: Map<string, ExportedFile>
	animationStorage: string[]
}

interface BoneIdEntry {
	uuid: string
	storageName: string
	id: string
}

interface IdMap {
	bones: BoneIdEntry[]
	locators: BoneIdEntry[]
}

export async function createAnimationStorageTsb(
	rig: IRenderedRig,
	animations: IRenderedAnimation[],
	opts: CreateAnimationStorageTsbOptions
): Promise<CreateAnimationStorageTsbResult> {
	const parsed = parseResourceLocation(opts.blueprintId)
	const fnNs = parsed.namespace
	const bpPath = parsed.path
	const storageNs = `${fnNs}.${bpPath}`
	const fnPathPrefix = `data/${fnNs}/functions/${bpPath}`
	const fnRef = `${fnNs}:${bpPath}`

	const files = new Map<string, ExportedFile>()
	const idMap = buildIdMap(rig)

	files.set(`${fnPathPrefix}/_bone_id_mapping.mcfunction`, {
		content: buildIdMappingComment(idMap, opts.blueprintId),
	})
	files.set(`${fnPathPrefix}/cleanup.mcfunction`, {
		content: buildCleanup(storageNs, opts.blueprintId, animations, fnRef),
	})

	const expandRefsByAnim: { anim: string; refs: string[] }[] = []
	const variantsExpandRefs: string[] = []

	for (const anim of animations) {
		const expandRefs = writeExpandFunctions(
			anim,
			idMap,
			opts,
			files,
			fnPathPrefix,
			fnRef,
			storageNs
		)
		expandRefsByAnim.push({ anim: anim.storage_name, refs: expandRefs })

		files.set(`${fnPathPrefix}/force_load/${anim.storage_name}.mcfunction`, {
			content: buildForceLoad(expandRefs),
		})

		const variantsContent = buildVariantsExpand(anim, rig, storageNs)
		if (variantsContent !== null) {
			files.set(
				`${fnPathPrefix}/expand_variants/${anim.storage_name}.mcfunction`,
				{ content: variantsContent }
			)
			variantsExpandRefs.push(`${fnRef}/expand_variants/${anim.storage_name}`)
		}
	}

	files.set(`${fnPathPrefix}/load/init_queue.mcfunction`, {
		content: buildInitQueue(
			expandRefsByAnim,
			variantsExpandRefs,
			storageNs,
			opts.blueprintId
		),
	})
	files.set(`${fnPathPrefix}/load/step.mcfunction`, {
		content: buildLoadStep(storageNs, fnRef),
	})
	files.set(`${fnPathPrefix}/load/rotate_active.mcfunction`, {
		content: buildRotateActive(opts.blueprintId),
	})
	files.set(`${fnPathPrefix}/load/remove_from_global.mcfunction`, {
		content: buildRemoveFromGlobal(opts.blueprintId),
	})
	files.set(`${fnPathPrefix}/load/pop/immediate.mcfunction`, {
		content: buildPop('immediate', storageNs, fnRef),
	})
	files.set(`${fnPathPrefix}/load/pop/high.mcfunction`, {
		content: buildPop('high', storageNs, fnRef),
	})
	files.set(`${fnPathPrefix}/load/pop/low.mcfunction`, {
		content: buildPop('low', storageNs, fnRef),
	})
	files.set(`${fnPathPrefix}/load/dispatch.mcfunction`, {
		content: buildDispatch(),
	})

	return { files, animationStorage: [] }
}

function buildIdMap(rig: IRenderedRig): IdMap {
	const bones: BoneIdEntry[] = []
	const locators: BoneIdEntry[] = []
	for (const node of Object.values(rig.nodes)) {
		if (BONE_TYPES.includes(node.type)) {
			bones.push({
				uuid: node.uuid,
				storageName: node.storage_name,
				id: bones.length.toString(36),
			})
		} else if (node.type === 'locator') {
			locators.push({
				uuid: node.uuid,
				storageName: node.storage_name,
				id: locators.length.toString(36),
			})
		}
	}
	return { bones, locators }
}

function buildIdMappingComment(idMap: IdMap, blueprintId: string): string {
	const lines = [
		`# Bone / locator ID mapping for blueprint ${blueprintId} (generated by Animated Java TSB Optimized Export).`,
		`# This file is documentation only and is not executed at runtime.`,
		`#`,
		`# [bones]`,
	]
	for (const b of idMap.bones) lines.push(`# ${b.id}: ${b.storageName}`)
	if (idMap.locators.length > 0) {
		lines.push(`#`, `# [locators]`)
		for (const l of idMap.locators) lines.push(`# ${l.id}: ${l.storageName}`)
	}
	return lines.join('\n') + '\n'
}

function buildCleanup(
	storageNs: string,
	bpId: string,
	animations: IRenderedAnimation[],
	fnRef: string
): string {
	// `data remove storage` はパス必須 + 対象が無いと throw するため、
	// 全 TSB データを固定ラッパー段 `d` 配下に置き、 execute if data でガードする。
	const kinds = ['anim', 'variants', 'state', 'tmp'] as const
	const storageLines = kinds.map(
		k => `execute if data storage ${storageNs}:${k} d run data remove storage ${storageNs}:${k} d`
	)
	// global キュー管理 storage 内の自 bp 痕跡も削除 (queue_order 内の {id:<bpId>} compound + active.<bpId>)。
	// 他 bp の登録には触らない (active list / queue_order は全 bp 共有なので bp 単位で部分削除する)。
	const bpIdLit = `"${escapeNbtString(bpId)}"`
	const orderSelector = `${GLOBAL_STORAGE_NS}:state d.queue_order[{id:${bpIdLit}}]`
	const activeRef = `${GLOBAL_STORAGE_NS}:state d.active.${bpIdLit}`
	const globalLines = [
		`execute if data storage ${orderSelector} run data remove storage ${orderSelector}`,
		`execute if data storage ${activeRef} run data remove storage ${activeRef}`,
	]
	const lines: string[] = [...storageLines, ...globalLines]
	// animation 単位の scoreboard objective 削除は AJ 既存の `remove_animation_objectives` を流用 (DRY)。
	// `tsb_silent_uninstall` フラグで UNINSTALL tellraw 抑制可。
	// 関数が生成されるのは has_animations のときだけなので、 animations が空なら呼ばない。
	if (animations.length > 0) {
		lines.push(`function ${fnRef}/remove_animation_objectives`)
	}
	return lines.join('\n') + '\n'
}

function writeExpandFunctions(
	anim: IRenderedAnimation,
	idMap: IdMap,
	opts: CreateAnimationStorageTsbOptions,
	files: Map<string, ExportedFile>,
	fnPathPrefix: string,
	fnRef: string,
	storageNs: string
): string[] {
	type Item = { line: string }
	const items: Item[] = []
	const animStorageName = anim.storage_name
	const cellsPerNode = anim.duration

	for (const b of idMap.bones) {
		if (!(b.uuid in anim.modified_nodes)) continue
		const framesObj = buildBoneFramesObj(b, anim, opts.quantizationDigits)
		if (framesObj === null) continue
		const line = `$data modify storage ${storageNs}:anim d.${animStorageName}.bones.${b.id}$(_) set value ${framesObj}`
		ensureLineWithinLimit(line, anim, b, opts.maxLineBytes)
		items.push({ line })
	}
	for (const l of idMap.locators) {
		if (!(l.uuid in anim.modified_nodes)) continue
		const framesObj = buildLocatorFramesObj(l, anim, opts.quantizationDigits)
		if (framesObj === null) continue
		const line = `$data modify storage ${storageNs}:anim d.${animStorageName}.locators.${l.id}$(_) set value ${framesObj}`
		ensureLineWithinLimit(line, anim, l, opts.maxLineBytes)
		items.push({ line })
	}

	const batches: Item[][] = []
	let current: Item[] = []
	let cells = 0
	for (const item of items) {
		if (cells + cellsPerNode > opts.cellsPerTick && current.length > 0) {
			batches.push(current)
			current = []
			cells = 0
		}
		current.push(item)
		cells += cellsPerNode
	}
	if (current.length > 0) batches.push(current)
	if (batches.length === 0) batches.push([])

	const refs: string[] = []
	for (let i = 0; i < batches.length; i++) {
		const isLast = i === batches.length - 1
		const body = batches[i].map(it => it.line).join('\n')
		const completionMark = isLast
			? `$data modify storage ${storageNs}:state d.loaded.${animStorageName}$(_) set value 1b`
			: ''
		const content = [body, completionMark].filter(Boolean).join('\n') + '\n'
		files.set(`${fnPathPrefix}/expand/${animStorageName}/p${i}.mcfunction`, {
			content,
		})
		refs.push(`${fnRef}/expand/${animStorageName}/p${i}`)
	}
	return refs
}

function ensureLineWithinLimit(
	line: string,
	anim: IRenderedAnimation,
	entry: BoneIdEntry,
	maxLineBytes: number
): void {
	const byteSize = Buffer.byteLength(line, 'utf8')
	if (byteSize > maxLineBytes) {
		throw new Error(
			`[TSB] Animation '${anim.storage_name}' の '${entry.storageName}' (id ${entry.id}) のフレーム数が多すぎ (1 行 ${byteSize} バイト > 上限 ${maxLineBytes})。 量子化精度を下げるか、 フレーム間引きするか、 アニメを分割してください。`
		)
	}
}

function buildBoneFramesObj(
	bone: BoneIdEntry,
	anim: IRenderedAnimation,
	digits: number
): string | null {
	const parts: string[] = []
	for (let i = 0; i < anim.frames.length; i++) {
		const transform = anim.frames[i].node_transforms[bone.uuid]
		if (!transform) continue
		// SVD 分解で 7 / 10 / 14 floats を cell 単位で自動振り分け (A-6 参照、 Phase B-1-shear)。
		// transform.matrix は THREE.Matrix4、 .elements が column-major 16 要素。
		const matrix = transform.matrix
		if (!matrix) continue
		const decomposed = decomposeTsb(matrix.elements as unknown as readonly number[], {
			quantizationDigits: digits,
		})
		const values = formatBoneCell(decomposed, digits)
		parts.push(`"${i}":[${values.join(',')}]`)
	}
	if (parts.length === 0) return null
	return `{${parts.join(',')}}`
}

/**
 * `decomposed` を scale_class に応じて 7 / 10 / 14 floats の文字列配列に整形する。
 *
 * - identity : translation 3 + left_rotation 4 = 7 floats (scale 全軸 ≒ 1 のため省略 + right_rotation = I)
 * - uniform  : 上記 + scale 3 = 10 floats (uniform scale のため right_rotation = I で省略可)
 * - non-uniform : 上記 + right_rotation 4 = 14 floats (shear ありうるので SVD で算出した R₂ を載せる)
 */
function formatBoneCell(d: DecomposedTsb, digits: number): string[] {
	const [tx, ty, tz] = d.translation
	const [qx, qy, qz, qw] = d.left_rotation
	const values: string[] = [
		formatTsbFloat(tx, digits),
		formatTsbFloat(ty, digits),
		formatTsbFloat(tz, digits),
		formatTsbFloat(qx, digits),
		formatTsbFloat(qy, digits),
		formatTsbFloat(qz, digits),
		formatTsbFloat(qw, digits),
	]
	if (d.scale_class === 'identity') return values
	const [sx, sy, sz] = d.scale
	values.push(formatTsbFloat(sx, digits), formatTsbFloat(sy, digits), formatTsbFloat(sz, digits))
	if (d.scale_class === 'uniform') return values
	const [rx, ry, rz, rw] = d.right_rotation
	values.push(
		formatTsbFloat(rx, digits),
		formatTsbFloat(ry, digits),
		formatTsbFloat(rz, digits),
		formatTsbFloat(rw, digits)
	)
	return values
}

function buildLocatorFramesObj(
	locator: BoneIdEntry,
	anim: IRenderedAnimation,
	digits: number
): string | null {
	const parts: string[] = []
	for (let i = 0; i < anim.frames.length; i++) {
		const transform = anim.frames[i].node_transforms[locator.uuid]
		if (!transform) continue
		const values = [
			formatTsbFloat(transform.pos[0], digits),
			formatTsbFloat(transform.pos[1], digits),
			formatTsbFloat(transform.pos[2], digits),
			formatTsbFloat(transform.rot[0], digits),
			formatTsbFloat(transform.rot[1], digits),
		]
		parts.push(`"${i}":[${values.join(',')}]`)
	}
	if (parts.length === 0) return null
	return `{${parts.join(',')}}`
}

function buildForceLoad(expandRefs: string[]): string {
	if (expandRefs.length === 0) return '\n'
	return expandRefs.map(r => `function ${r} {_: ""}`).join('\n') + '\n'
}

function buildVariantsExpand(
	anim: IRenderedAnimation,
	rig: IRenderedRig,
	storageNs: string
): string | null {
	const parts: string[] = []
	for (let i = 0; i < anim.frames.length; i++) {
		const frame = anim.frames[i]
		if (!frame.variants || frame.variants.length === 0) continue
		const variantUuid = frame.variants[0]
		const variant = rig.variants[variantUuid]
		if (!variant) continue
		const name = escapeNbtString(variant.name)
		const condition = frame.variants_execute_condition
			? escapeNbtString(`${frame.variants_execute_condition} `)
			: ''
		parts.push(`"${i}":{name:"${name}",condition:"${condition}"}`)
	}
	if (parts.length === 0) return null
	return (
		[
			`$data modify storage ${storageNs}:variants d.${anim.storage_name}$(_) set value {${parts.join(',')}}`,
			`$data modify storage ${storageNs}:state d.loaded_variants.${anim.storage_name}$(_) set value 1b`,
		].join('\n') + '\n'
	)
}

function buildInitQueue(
	expandRefsByAnim: { anim: string; refs: string[] }[],
	variantsExpandRefs: string[],
	storageNs: string,
	bpId: string
): string {
	const immediate: string[] = []
	const high: string[] = []
	const low: string[] = []
	for (const { refs } of expandRefsByAnim) low.push(...refs)
	for (const v of variantsExpandRefs) low.push(v)

	const formatList = (arr: string[]): string =>
		arr.length === 0 ? '[]' : `[${arr.map(r => `"${r}"`).join(',')}]`

	// 自 bp queue を完全上書き。 旧 datapack で展開途中だったキューの残骸は data modify set value
	// の単純 replace で破棄される (MC ソース確認 : NbtPathArgument.java:621 の deep copy + CompoundTag.put、
	// O(N) で副作用なし、 merge 経路に乗らない)。 削除アニメへの古い expand 参照もここで消える。
	const lines = [
		`data modify storage ${storageNs}:state d.queue.immediate set value ${formatList(immediate)}`,
		`data modify storage ${storageNs}:state d.queue.high set value ${formatList(high)}`,
		`data modify storage ${storageNs}:state d.queue.low set value ${formatList(low)}`,
	]
	if (immediate.length + high.length + low.length > 0) {
		// global active set に自分を登録 (重複ガード) + queue_order に compound エントリで append。
		// queue_order は compound list ({id:"<bp>"}) なので、 cleanup 時 [{id:"<bp>"}] selector で
		// 値一致削除できる (string list だと値一致削除が MC vanilla で不可)。
		// schedule は不要 : animated_java:global/load_tick が minecraft:tick タグで常駐し、
		// queue_order を毎 tick 監視して round-robin で各 bp の load/step を呼ぶ。
		const bpIdLit = `"${escapeNbtString(bpId)}"`
		lines.push(
			`execute unless data storage ${GLOBAL_STORAGE_NS}:state d.active.${bpIdLit} run data modify storage ${GLOBAL_STORAGE_NS}:state d.queue_order append value {id:${bpIdLit}}`,
			`data modify storage ${GLOBAL_STORAGE_NS}:state d.active.${bpIdLit} set value 1b`
		)
	}
	return lines.join('\n') + '\n'
}

function buildLoadStep(storageNs: string, fnRef: string): string {
	const im = `${storageNs}:state d.queue.immediate[0]`
	const hi = `${storageNs}:state d.queue.high[0]`
	const lo = `${storageNs}:state d.queue.low[0]`
	// 1 step = 1 pop + dispatch。 末尾で自 bp queue 残量を見て、 残っているなら round-robin
	// (先頭の自エントリを末尾に移動)、 全空なら global active list から自分を削除する。
	return (
		[
			`execute if data storage ${im} run return run function ${fnRef}/load/pop/immediate`,
			`execute if data storage ${hi} run return run function ${fnRef}/load/pop/high`,
			`execute if data storage ${lo} run function ${fnRef}/load/pop/low`,
			``,
			`execute if data storage ${im} run return run function ${fnRef}/load/rotate_active`,
			`execute if data storage ${hi} run return run function ${fnRef}/load/rotate_active`,
			`execute if data storage ${lo} run return run function ${fnRef}/load/rotate_active`,
			`function ${fnRef}/load/remove_from_global`,
		].join('\n') + '\n'
	)
}

function buildRotateActive(bpId: string): string {
	const bpIdLit = `"${escapeNbtString(bpId)}"`
	return (
		[
			`data remove storage ${GLOBAL_STORAGE_NS}:state d.queue_order[0]`,
			`data modify storage ${GLOBAL_STORAGE_NS}:state d.queue_order append value {id:${bpIdLit}}`,
		].join('\n') + '\n'
	)
}

function buildRemoveFromGlobal(bpId: string): string {
	const bpIdLit = `"${escapeNbtString(bpId)}"`
	return (
		[
			`data remove storage ${GLOBAL_STORAGE_NS}:state d.queue_order[0]`,
			`data remove storage ${GLOBAL_STORAGE_NS}:state d.active.${bpIdLit}`,
		].join('\n') + '\n'
	)
}

function buildPop(
	priority: 'immediate' | 'high' | 'low',
	storageNs: string,
	fnRef: string
): string {
	return (
		[
			`data modify storage ${storageNs}:tmp d.pop set from storage ${storageNs}:state d.queue.${priority}[0]`,
			`data remove storage ${storageNs}:state d.queue.${priority}[0]`,
			`function ${fnRef}/load/dispatch with storage ${storageNs}:tmp d`,
		].join('\n') + '\n'
	)
}

function buildDispatch(): string {
	return `$function $(pop) {_: ""}\n`
}

function formatTsbFloat(n: number, digits: number): string {
	if (!Number.isFinite(n)) return '0f'
	const s = `${n.toFixed(digits).replace(/\.?0+$/, '')}f`
	if (s.startsWith('-0.')) return `-${s.slice(2)}`
	if (s.startsWith('0.')) return s.slice(1)
	return s
}

function escapeNbtString(s: string): string {
	return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}
